auto_training_fixdata:
  project_name: "auto_training_fixdata"
  fixed_win: 15

LastTokenNN:
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.8
W2qLastTokenNN:
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.6