auto_training_fixdata:
  project_name: "auto_training_fixdata"
  fixed_win: 15

TraditionalNN:
    name: Traditional
    best: !!int 3
    seed: !!int 41
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.5

WithoutAttentionNN:
    name: WithoutAttention
    best: !!int 4
    seed: !!int 43
    numhead: !!int 0
    atten_dropout: 0
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.8
    
LastTokenNN:
    name: LastToken
    best: !!int 14
    seed: !!int 38
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.9

W2qLastTokenNN:
    name: W2qLastToken
    best: !!int 65
    seed: !!int 40
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.75

MTCrossModelNN: 
    name: MTCrossModel
    best: !!int 7
    seed: !!int 40
    numhead: !!int 4
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.8

ShareLastTokenNN:
    name: ShareLastToken
    best: !!int 34
    seed: !!int 42
    numhead: !!int 4
    share_feature: 24
    atten_dropout: 0.2
    cls_dropout: 0.1
    reg_dropout: 0.1
    weight_decay: 0.0
    learning_rate: !!float 1e-3
    w_reg: 0.85